/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wit_ctw_NativeJni */

#ifndef _Included_com_wit_ctw_NativeJni
#define _Included_com_wit_ctw_NativeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wit_ctw_NativeJni
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wit_ctw_NativeJni_multiply
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
